### PR TITLE
Don't ignore errors in str_path_to_cfstring_ref

### PR DESCRIPTION
**Pull request by Marwes**
Ignoring the errors can lead to segfaults as the returned value is null
in those cases.

Specifically I have gotten
`Error Domain=NSCocoaErrorDomain Code=4 \"The file doesn’t exist.\"`
from `CFURLCreateFileReferenceURL`. It is difficult to reproduce but I
think it can happen if the watched directory gets deleted while the
function is called. Regardless of how it occurs the errors should at least be handled.

### CODE REVIEW

**Comment by octplane** [comment]
Thanks for your thorough investigation!

**Comment by octplane** [comment]
- The test you added fails. It that expected?

**Comment by Marwes** [comment]
Sorry about that, I thought I removed that test after I didn't succeed at getting a reproduction.

**Comment by octplane** [comment]
👍

**Pull request merged**
